### ISSUE TITLE
TODO über die ferien.

### ISSUE THREAD

**Issue by Hoppix** [Hoppix/3d_Cube#3]
- [ ] Plane und Cube als einzelne Objekte //Jonas

- [ ] Lichtquellen fixen //Kolja

- [ ] Textur für 1 Objekt //Marina

- [ ] Texturen für 2 Objekte

- [ ] Normal-Map implementieren

- [ ] optional: .obj-loader
